name: "HTML5 Validator"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: HTML5Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.1.1
        with:
          root: /
          css: true
        continue-on-error: true
      - name: Update logs
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'log.log'
          destination_repo: 'mrepol742/mrepol742.github.io'
          user_email: 'mrepol742@gmail.com'
          user_name: 'mrepol742'
          commit_message: 'Initial Commit'
          destination_branch: log
